name = "EqualityConstrainedMinimization"
uuid = "3687fdae-f7fc-44d6-b290-5a4209d5cae9"
authors = ["Isaac Hawn <ihawn.pl15@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
